blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/conference-hall/conference-hall/discussions/new?category=ideas-and-features
    about: We appreciate you taking the time to improve Conference Hall with your ideas, but we
      use the Discussions for this instead of the issues tab ğŸ™‚.
  - name: ğŸ™ Get Help
    url: https://github.com/conference-hall/conference-hall/discussions/new?category=q-a
    about: If you can't get something to work the way you expect, open a question in
      the Conference Hall discussions.
